// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlX8LvM98lCTaxUVLs71yrjHKyyweSQbQ',
    appId: '1:681222060242:web:31f43e69242c7a9b24d50b',
    messagingSenderId: '681222060242',
    projectId: 'blocexpensetracker',
    authDomain: 'blocexpensetracker.firebaseapp.com',
    storageBucket: 'blocexpensetracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxgwmkzjfPGr92uFjAsb1Mfqh_csYhBHs',
    appId: '1:681222060242:android:8b4d9a5bb0a77fd224d50b',
    messagingSenderId: '681222060242',
    projectId: 'blocexpensetracker',
    storageBucket: 'blocexpensetracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnjV39U7nsHB0Gnh4Nrwe_zC4ihqW-cDY',
    appId: '1:681222060242:ios:fb83585b5dc8eff524d50b',
    messagingSenderId: '681222060242',
    projectId: 'blocexpensetracker',
    storageBucket: 'blocexpensetracker.firebasestorage.app',
    iosBundleId: 'com.example.blocExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnjV39U7nsHB0Gnh4Nrwe_zC4ihqW-cDY',
    appId: '1:681222060242:ios:fb83585b5dc8eff524d50b',
    messagingSenderId: '681222060242',
    projectId: 'blocexpensetracker',
    storageBucket: 'blocexpensetracker.firebasestorage.app',
    iosBundleId: 'com.example.blocExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlX8LvM98lCTaxUVLs71yrjHKyyweSQbQ',
    appId: '1:681222060242:web:6a4fabd9091cab6d24d50b',
    messagingSenderId: '681222060242',
    projectId: 'blocexpensetracker',
    authDomain: 'blocexpensetracker.firebaseapp.com',
    storageBucket: 'blocexpensetracker.firebasestorage.app',
  );
}
